CC=g++
GTEST_DIR=<insert google test dir>
CFLAGS=-c -Wall -I./ -I$(GTEST_DIR)/include
LDFLAGS=-L$(GTEST_DIR) -lgtest
SOURCES := test.cpp Read.cpp VariantFromSAM.cpp
OBJECTS=$(SOURCES:.cpp=.o)
test: $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@
